### ISSUE TITLE
We need to relaunch and extend the project

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-corrector#5]
We have a load more data than when this project was launched.

Here's the ongoing discussion #quality in the Slack

@stephanegigandet @nicolasleger 

https://github.com/openfoodfacts/openfoodfacts-server/issues/912

**Comment by nicolasleger** [comment]
Hello, we might search for similar tool with correcting rules in other data / classification project.

**Comment by nicolasleger** [comment]
@teolemon can you make me admin of this repository please?

**Comment by teolemon** [comment]
done.
The idea would be to read the ingredient list for each product, perform quality checks, and add a special label if an issue is detected.
- https://github.com/openfoodfacts/openfoodfacts-server/issues/912
